FROM ubuntu:20.04

# Install some basic utilities
RUN apt-get update && apt-get install -y \
    curl \
    ca-certificates \
    sudo \
    git \
    bzip2 \
    libx11-6 \
 && rm -rf /var/lib/apt/lists/*

# Create a working directory
RUN mkdir /app
WORKDIR /app

# Create a non-root user and switch to it
RUN adduser --disabled-password --gecos '' --shell /bin/bash user \
 && chown -R user:user /app
RUN echo "user ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/90-user
USER user

# All users can use /home/user as their home directory
ENV HOME=/home/user
RUN chmod 777 /home/user

# Set up the Conda environment
ENV CONDA_AUTO_UPDATE_CONDA=false \
    PATH=/home/user/miniconda/bin:$PATH
COPY environment.yml /app/environment.yml
RUN curl -sLo ~/miniconda.sh https://repo.continuum.io/miniconda/Miniconda3-py39_4.10.3-Linux-x86_64.sh \
 && chmod +x ~/miniconda.sh \
 && ~/miniconda.sh -b -p ~/miniconda \
 && rm ~/miniconda.sh \
 && conda env update -n base -f /app/environment.yml \
 && rm /app/environment.yml \
 && conda clean -ya

COPY . .

RUN pip3 install -r requirements.txt

RUN ls /app

ARG WEBSERVICE_HOST="0.0.0.0"
ARG WEBSERVICE_PORT=5000

ENV PYTHONPATH /app
ENV WEBSERVICE_HOST ${WEBSERVICE_HOST}
ENV WEBSERVICE_PORT ${WEBSERVICE_PORT}

RUN echo $PYTHONPATH
RUN echo $WEBSERVICE_HOST
RUN echo $WEBSERVICE_PORT

CMD ["python3", "create_webservice.py"]

EXPOSE ${WEBSERVICE_PORT}